# Generated by Django 3.1.4 on 2021-04-28 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210428_0159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
