# Generated by Django 3.1.4 on 2021-05-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210522_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
