# Generated by Django 3.1.4 on 2021-05-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Addres',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
