# Generated by Django 3.1.4 on 2021-05-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210522_1857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
