# Generated by Django 3.1.4 on 2021-05-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210524_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
